auth:
  acl:
  - path: .?
    users:
    - any
    methods:
    - GET
    contenttype:
    - any
  - path: ^/subjects/999-9\.[a-z0-9-]+\.(db|cdc|cmd|sys|log|tmp)\.[a-z0-9-.]+\.\d+-(key|value).*$
    users:
    - sre-sr-manager
    methods:
    - post
    contenttype:
    - any
  - path: ^/compatibility/subjects/999-9\.[a-z0-9-]+\.(db|cdc|cmd|sys|log|tmp)\.[a-z0-9-.]+\.\d+-(key|value).*$
    users:
    - any
    methods:
    - post
    contenttype:
    - any
